version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=422193507691.dkr.ecr.us-east-1.amazonaws.com/paperless-aws

  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Going to push docker image
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"paperless-aws","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files:
    - target/*.jar
    - imagedefinitions.json
    - appspec.yml
    - scripts/pulldocker